### ISSUE TITLE
Tutorial on how to create a custom drone model for Gazebo

### ISSUE THREAD

**Issue by stibipet** [ctu-mrs/ctu-mrs.github.io#8]
- [x] how to derive a custom platform
- [x] how to add a custom component
- [x] how to make it compatible with MRS Drone Spawner
- [x] how to do it from an external repo

**Comment by stibipet** [comment]
Step-by-step tutorial here: https://ctu-mrs.github.io/docs/simulation/gazebo/gazebo/custom_drone.html
Example repo here: https://github.com/ctu-mrs/mrs_gazebo_custom_drone_example

**Comment by klaxalk** [comment]
Thanks, this is a huge improvement of the system!
